### PR TITLE
User friendly extension

### PR DESCRIPTION
**Pull request by EricStrohmaier**

### CODE REVIEW

**Comment by EricStrohmaier** [comment]
ups I how did i make a branch here ? haha ups

**Comment by EricStrohmaier** [comment]
Anyway.  I made some styles to the Pop-up and prompt window.
Because i didn't know what to do with the extension when i first downloaded it ... 
and thinking about making a user "Signup" page where the user can easily generate keys, and it's saved straight into extension! 

Actually, I already made the pop-up for signup 
(not sure if @fiatjaf wants to continue in this direction of creating users) 



Screenshot 2023-10-20 at 1 32 39 PM
Screenshot 2023-10-20 at 1 33 18 PM
Screenshot 2023-10-20 at 1 33 56 PM

Uploading Screen Recording 2023-10-20 at 1.35.45 PM.mov…

**Comment by EricStrohmaier** [comment]
https://github.com/fiatjaf/nos2x/assets/122783162/f415fa0a-0d6d-4fec-91b3-63790a73da04

**Comment by fiatjaf** [comment]
Thank you, the designs look good, but I don't want them.
I do want the "create user" popup, but only if it's built with vanilla HTML.

**Comment by EricStrohmaier** [comment]
Do you mean the create user workflow or just the popup function ? 
(With metadata or just generate keys and save them to the extension) 
Why plain Js if I may ask 😅

**Comment by EricStrohmaier** [comment]
@fiatjaf  Hey sorry it took me so long because I couldnt figure out how to create a user with metadata + send the info to the relays ... I would need more time to look into it and dont have that right now :(( 

anyway in the commit [c92a18c](https://github.com/fiatjaf/nos2x/pull/50/commits/c92a18cfcf4765205543457dbc0ccb2ff13996fe)  you could  just provide the logic for the publishing user with metadata to relays.

The latest commit is just creating a naked key and then saving it in extension   => Ready to go!

If you could help me out that would mean the world to me if not not.
I am planing to make a version of this extension with some styles for me and people I tell how to use Nostr    but it needs some more simplicity. "User friendliness"

**Comment by fiatjaf** [comment]
No, sorry, what I meant was that the extension should just create the key, not the metadata. The metadata can be edited in clients.

This PR should be good now, I'll check it out later and merge.

**Comment by EricStrohmaier** [comment]
Okay perfect.  But keep in mind that I changed the popup window for signing ....  I put it in the middle of screen plus some small styles I think that I didn't revert ....

**Comment by EricStrohmaier** [comment]
should be good now!

**Comment by EricStrohmaier** [comment]
https://www.loom.com/share/8a52c587cfc643f9aee31d5b3401620b?sid=471e3bf3-99ce-4b0e-a854-b4136dd23bed

**Pull request merged**
